/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diandi_klob_ndkshare_Engine */

#ifndef _Included_com_diandi_klob_ndkshare_Engine
#define _Included_com_diandi_klob_ndkshare_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diandi_klob_ndkshare_Engine
 * Method:    callJNIInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_diandi_klob_ndkshare_Engine_callJNIInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_diandi_klob_ndkshare_Engine
 * Method:    callJNIInt
 * Signature: (II)V
 */

JNIEXPORT void JNICALL Java_com_diandi_klob_ndkshare_Engine_callJNIString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_diandi_klob_ndkshare_Engine
 * Method:    md5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_diandi_klob_ndkshare_Engine_md5
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_diandi_klob_ndkshare_Engine
 * Method:    test3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_diandi_klob_ndkshare_Engine_test3
  (JNIEnv *, jobject);

/*
 * Class:     com_diandi_klob_ndkshare_Engine
 * Method:    test4
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_diandi_klob_ndkshare_Engine_test4
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
